select:
  num_replicates: None
  num_train_samples:
    start : None
    stop : None
    step : None
  num_test_samples: None

    models:
    -
      model: svm
      feature_list_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
      hyperparameters:
        C : None
        gamma : None

  todo_list:
    -
      feature_file : summary_feature_file_created_220114_220505
      output_dir: /Users/rsankar/Desktop/HVCHackathon/HVC/HVC_out/extract_output_220114_220444